<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>


<h2>Puzzle Solution</h2>

<div class="panel">
  	<div class="panel-body">
  		<div class="col-md-7">
  			<div id="gameObject"></div>
		</div>
		<div class="col-md-3">
			<div class="gamePanel2">
				Total Steps:
				<span id="totalSteps">0</span>			
			</div>
			<div class="gamePanel2">
				Current Step:
				<span id="currStep">0</span>			
			</div>
			<br />
			<div class="gamePanel2">
		    	<button id="prev" type="button" class="btn btn-primary" disabled>&laquo; Previous</button>
		    	<button id="next" type="button" class="btn btn-primary">Next &raquo;</button>
		    </div>
		</div>
	</div>
	<div>
		<h4>Notes:</h4>
		<p>This solution is generated by the A* search algorithm.</p>
	</div>	
</div>

<script>
$(document).ready(function() {
	var size = ${puzzleSize};
	
	// pixels of the game board
	var boardSize = 600;

	// empty space of the board (gray)
	var emptyTile = size * size;

	// pixels of each tile
	var tileSize = boardSize / size;
	
	var image = "${image}";
	var boards = [];
	boards = ${solution};
	// console.log(boards[0]);
	
	var total = boards.length - 1;
	var curr = 0;
	//console.log(total);
	
	$.fn.extend({ puzzle_solution:
    	function() {
	    	// set game board
	    	$("#gameObject").html('<div id="board"></div>');
	
	    	$("#board").css({ 
		        position:"absolute", 
		        width: boardSize + "px", 
		        height: boardSize + "px", 
		        border: "2px solid gray"
		    });
	    	
	    	initSolution();
	    		
	        $("#prev").click(function() {
	        	if (curr == total) {
 					$("#next").removeAttr("disabled");
 				}
	        	
	        	if (curr != 0) {
	        		setBoard(boards[--curr]);
	        		$("#currStep").text(curr);
	        		if (curr == 0) {
	        			$("#prev").prop("disabled", true);
	        		}
	        	}
	        });
	        
 			$("#next").click(function() {
 				if (curr == 0) {
 					$("#prev").removeAttr("disabled");
 				}
	        	
 			    if (curr != total) {
 			    	setBoard(boards[++curr]);
	        		$("#currStep").text(curr);
	        		if (curr == total) {
	        			$("#next").prop("disabled", true);
	        		}
 			    }
	        });  
        }
    });
	
    function initSolution() {
    	// create all tiles in order
    	for (var j = 0; j < emptyTile - 1; j++) {
    		tile = $("<div><br /></div>");
    		var xPos = (j % size) * tileSize,
			    yPos = Math.floor(j / size) * tileSize;
    		
    		var xImagePos = -(j % size) * tileSize,
    			yImagePos = -Math.floor(j / size) * tileSize;
    	
	        tile.css({
	     		display: "block",
	     		float: "left",
	     		cursor: "pointer",
	     		backgroundImage: "url(../resources/puzzleimages/" + image + ")",
	     		backgroundRepeat: "no-repeat",
	     		backgroundPosition: (xImagePos + "px " + yImagePos + "px"),
	     		position: "absolute",
	     		left: xPos + "px",
	     		top: yPos + "px",
	     		mozUserSelect: "none",
	     		webkitUserSelect: "none",
	     		khtmlUserSelect: "none",
	     		userSelect: "none",
	     		border: "1px solid gray"
	     	}).width(tileSize).height(tileSize);
    		
            $("#board").append(tile);
    	}
    	
		// set empty space transparent
		space = $("<div><br /></div>");
		space.css({
	 		display: "block",
	 		float: "left",
	 		cursor: "pointer",
	 		background: "transparent",
	 		position: "absolute",
	 		left: ((emptyTile - 1) % size) * tileSize + "px",
     		top: Math.floor((emptyTile - 1) / size) * tileSize + "px",
	 		mozUserSelect: "none",
	 		webkitUserSelect: "none",
	 		khtmlUserSelect: "none",
	 		userSelect: "none"
	 	}).width(tileSize).height(tileSize);
		
		$("#board").append(space);
		
		// shuffle to initState
		setBoard(boards[0]);
		$("#totalSteps").text(total);
		$("#currStep").text(0);
    }
    
    function setBoard(boardStr) {
    	var board = [];
    	board = boardStr.split(",");
		
    	for (var j = 0; j < emptyTile; j++) {
    		
    		var xNew = (j % size) * tileSize,
	    		yNew = Math.floor(j / size) * tileSize;
    		
    		if (board[j] == 0) {
    			$("#board").children("div:nth-child(" + emptyTile + ")").css("left", xNew);
    			$("#board").children("div:nth-child(" + emptyTile + ")").css("top", yNew);
    		}
    		else {	
    			$("#board").children("div:nth-child(" + board[j] + ")").css("left", xNew);
    			$("#board").children("div:nth-child(" + board[j] + ")").css("top", yNew);
    		}
    	}
    }
	
	$("#gameObject").puzzle_solution();
});
</script>

